//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymify.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource_u {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_u() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gymify.Web.Resources.SharedResource.u", typeof(SharedResource_u).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть коректну електронну пошту..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тривалість у хвилинах має бути невід&apos;ємним числом..
        /// </summary>
        public static string Msg_DurationPositive {
            get {
                return ResourceManager.GetString("Msg_DurationPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь ласка, введіть назву вправи..
        /// </summary>
        public static string Msg_ExerciseNameRequired {
            get {
                return ResourceManager.GetString("Msg_ExerciseNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва вправи не може бути коротшою за 3 та довшою за 100 символів..
        /// </summary>
        public static string Msg_NameLength {
            get {
                return ResourceManager.GetString("Msg_NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немає вправ для збереження..
        /// </summary>
        public static string Msg_NoExercisesToSave {
            get {
                return ResourceManager.GetString("Msg_NoExercisesToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кожна вправа повинна мати принаймні одне позитивне значення (повторення, вага або тривалість)..
        /// </summary>
        public static string Msg_RepsOrWeightOrDurationRequiredForAtLeastOne {
            get {
                return ResourceManager.GetString("Msg_RepsOrWeightOrDurationRequiredForAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість повторень має бути невід&apos;ємним числом..
        /// </summary>
        public static string Msg_RepsPositive {
            get {
                return ResourceManager.GetString("Msg_RepsPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість підходів має бути від 1 до 100..
        /// </summary>
        public static string Msg_SetsMustBePositive {
            get {
                return ResourceManager.GetString("Msg_SetsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість підходів (Sets) є обов&apos;язковою..
        /// </summary>
        public static string Msg_SetsRequired {
            get {
                return ResourceManager.GetString("Msg_SetsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося зберегти вправи через помилки:.
        /// </summary>
        public static string Msg_ValidationFailedTitle {
            get {
                return ResourceManager.GetString("Msg_ValidationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вага має бути невід&apos;ємним числом..
        /// </summary>
        public static string Msg_WeightPositive {
            get {
                return ResourceManager.GetString("Msg_WeightPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва має бути від {2} до {1} символів..
        /// </summary>
        public static string NameLength {
            get {
                return ResourceManager.GetString("NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль повинен мати мінімум {1} символів..
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролі не співпадають..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} є обов&apos;язковим..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нікнейм має бути від {2} до {1} символів..
        /// </summary>
        public static string UserNameLength {
            get {
                return ResourceManager.GetString("UserNameLength", resourceCulture);
            }
        }
    }
}
